# ruff.toml

[tool.ruff]
select = ["E", "F", "W", "C901"]
target-version = "py312"  # Target Python 3.12
max-line-length = 120  

# Per-file ignores
[tool.ruff.per-file-ignores]
"tests/*" = ["F401", "F403"]  # Ignore specific errors for test files
